@API_URL = https://video-management-api-nslz.onrender.com

###

POST {{API_URL}}/videos
Content-Type: application/json

{
    "title": "video 01",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

GET {{API_URL}}/videos

###

PUT {{API_URL}}/videos/3e422c08-4761-4c71-b1c9-73c74fa4fa89
Content-Type: application/json

{
    "title": "video teste",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

DELETE {{API_URL}}/videos/3e422c08-4761-4c71-b1c9-73c74fa4fa89